### ISSUE TITLE
Huho

### ISSUE THREAD

**Issue by Naereen** [pcotret/pcotret.github.io#1]
![gifrecord_2017-08-29_135019](https://user-images.githubusercontent.com/11994719/29819443-1bcf6cf8-8cc1-11e7-83fc-2fce28f24c8b.gif)

**Comment by Naereen** [comment]
(Note : ma souris bouge pas)

**Comment by pcotret** [comment]
C'est quoi comme Firefox ?
Perso, pas de soucis sur Firefox/Chrome. Et si le zoom est vraiment trop grand, c'est responsive et ça passe en mise en page verticale :/

**Comment by Naereen** [comment]
Pas de soucis sous Chrome en effet. Mais dès que j'ai 2 colonnes sous Firefox (50.1, XUbuntu) ça foire.
Mais t'en fais pas alors, ça doit être que moi.

Sur un autre Firefox (Tor browser) le soucis est plus là.
